# Generated by Django 4.2.29 on 2026-03-18 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address_user_fullname_user_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
