# Generated by Django 4.2.29 on 2026-03-18 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_fullname_user_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
