# Generated by Django 4.2.29 on 2026-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
    ]
