# Generated by Django 4.2.29 on 2026-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_vehicle_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="insurance/documents/"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="bluebook",
            field=models.FileField(
                blank=True, null=True, upload_to="vehicles/documents/"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicles/images/"
            ),
        ),
    ]
